include:
  - jpo-utils/docker-compose.yml

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  ode:
    profiles:
      - all
      - ode_full
      - ode_base
      - ode
    build: .
    image: jpoode_ode:latest
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    ports:
      - "8080:8080"
      - "9090:9090"
      - "46753:46753/udp"
      - "46800:46800/udp"
      - "47900:47900/udp"
      - "44900:44900/udp"
      - "44910:44910/udp"
      - "44920:44920/udp"
      - "44930:44930/udp"
      - "44940:44940/udp"
      - "44990:44990/udp"
      - "5555:5555/udp"
      - "6666:6666/udp"
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      ODE_KAFKA_BROKERS: ${DOCKER_HOST_IP}:9092
      ODE_SECURITY_SVCS_SIGNATURE_URI: ${ODE_SECURITY_SVCS_SIGNATURE_URI}
      ODE_RSU_USERNAME: ${ODE_RSU_USERNAME}
      ODE_RSU_PASSWORD: ${ODE_RSU_PASSWORD}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      DATA_SIGNING_ENABLED_RSU: ${DATA_SIGNING_ENABLED_RSU}
      DATA_SIGNING_ENABLED_SDW: ${DATA_SIGNING_ENABLED_SDW}
      DEFAULT_SNMP_PROTOCOL: ${DEFAULT_SNMP_PROTOCOL}
      KAFKA_LINGER_MS: ${KAFKA_LINGER_MS}
      ODE_TIM_INGEST_MONITORING_ENABLED: true
      ODE_TIM_INGEST_MONITORING_INTERVAL: 1
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://${DOCKER_HOST_IP}:4318/v1/traces
    depends_on:
      kafka:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/jpo-ode
      - ${DOCKER_SHARED_VOLUME}/uploads:/home/uploads
    healthcheck:
      test: ["CMD", "wget" ,"--spider", "http://localhost:8080"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  adm:
    profiles:
      - all
      - ode_full
      - ode_base
      - adm
    image: us.gcr.io/cdot-oim-cv-dev/jpoode_acm-image:asn1_codec-develop-branch-12-16-2024t09.22mdt
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_TYPE: ${KAFKA_TYPE}
      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}
      ACM_CONFIG_FILE: adm.properties
      ACM_LOG_TO_CONSOLE: ${ADM_LOG_TO_CONSOLE}
      ACM_LOG_TO_FILE: ${ADM_LOG_TO_FILE}
      ACM_LOG_LEVEL: ${ADM_LOG_LEVEL}
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/asn1_codec_share
    logging:
      options:
        max-size: "10m"
        max-file: "5"
