version: '3'
services:
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka:/bitnami
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9094,CONTROLLER://:9093,EXTERNAL://:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9094,EXTERNAL://${DOCKER_HOST_IP}:9092"
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_LOG_RETENTION_HOURS: 2
    logging:
      options:
        max-size: "10m"  
        max-file: "5"

  kafka_init:
    image: bitnami/kafka:latest
    depends_on:
      kafka:
        condition: service_started
    volumes:
      - ./scripts/kafka/kafka_init.sh:/kafka_init.sh
    entrypoint: ["/bin/sh", "kafka_init.sh"]

  ode:
    build: .
    image: jpoode_ode:latest
    ports:
      - "8080:8080"
      - "9090:9090"
      - "46753:46753/udp"
      - "46800:46800/udp"
      - "47900:47900/udp"
      - "44900:44900/udp"
      - "44910:44910/udp"
      - "44920:44920/udp"
      - "44930:44930/udp"
      - "44940:44940/udp"
      - "5555:5555/udp"
      - "6666:6666/udp"
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      ZK: ${DOCKER_HOST_IP}:2181
      ODE_SECURITY_SVCS_SIGNATURE_URI: ${ODE_SECURITY_SVCS_SIGNATURE_URI}
      ODE_RSU_USERNAME: ${ODE_RSU_USERNAME}
      ODE_RSU_PASSWORD: ${ODE_RSU_PASSWORD}
      DATA_SIGNING_ENABLED_RSU: ${DATA_SIGNING_ENABLED_RSU}
      DATA_SIGNING_ENABLED_SDW: ${DATA_SIGNING_ENABLED_SDW}
      DEFAULT_SNMP_PROTOCOL: ${DEFAULT_SNMP_PROTOCOL}
    depends_on:
      - kafka
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/jpo-ode
      - ${DOCKER_SHARED_VOLUME}/uploads:/home/uploads
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  adm:
    build: ./asn1_codec
    image: jpoode_acm:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      ACM_CONFIG_FILE: adm.properties
      ACM_LOG_TO_CONSOLE: ${ADM_LOG_TO_CONSOLE}
      ACM_LOG_TO_FILE: ${ADM_LOG_TO_FILE}
      ACM_LOG_LEVEL: ${ADM_LOG_LEVEL}
    depends_on:
      - kafka
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/asn1_codec_share
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    restart: on-failure

  aem:
    build: ./asn1_codec
    image: jpoode_acm:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      ACM_CONFIG_FILE: aem.properties
      ACM_LOG_TO_CONSOLE: ${AEM_LOG_TO_CONSOLE}
      ACM_LOG_TO_FILE: ${AEM_LOG_TO_FILE}
      ACM_LOG_LEVEL: ${AEM_LOG_LEVEL}
    depends_on:
      - kafka
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/asn1_codec_share
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    restart: on-failure

  ppm_bsm:
    build:
      context: ./jpo-cvdp
      dockerfile: Dockerfile
    image: jpoode_ppm:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      PPM_CONFIG_FILE: ppmBsm.properties
      PPM_LOG_TO_CONSOLE: ${PPM_BSM_LOG_TO_CONSOLE}
      PPM_LOG_TO_FILE: ${PPM_BSM_LOG_TO_FILE}
      PPM_LOG_LEVEL: ${PPM_BSM_LOG_LEVEL}
    volumes:
      - ${DOCKER_SHARED_VOLUME}:/ppm_data
    depends_on:
      - kafka
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  sdw_depositor:
    build: ./jpo-sdw-depositor
    image: jpoode_sdwdep:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      #SDW_GROUP_ID: ${SDW_GROUP_ID}
      #SDW_KAFKA_PORT: ${SDW_KAFKA_PORT}
      #SDW_SUBSCRIPTION_TOPICS: ${SDW_SUBSCRIPTION_TOPICS}
      #SDW_DESTINATION_URL: ${SDW_DESTINATION_URL}
      SDW_API_KEY: ${SDW_API_KEY}
    depends_on:
     - kafka
     - ode
    logging:
      options:
        max-size: "10m" 
        max-file: "5"

  sec:
    build: ./jpo-security-svcs
    image: jpoode_sec:latest
    ports:
     - "8090:8090"
    environment:
      SEC_CRYPTO_SERVICE_BASE_URI: ${SEC_CRYPTO_SERVICE_BASE_URI}
    logging:
      options:
        max-size: "10m"  
        max-file: "5"

volumes:
  kafka:
    {}