---
apiVersion: v1
kind: Service
metadata:
  name: jpoode-ode-tcp-svc
  labels:
    app: jpoode-ode
spec:
  type: LoadBalancer 
  ports:
  - name: ode-scp
    protocol: TCP
    port: 22
  - name: ode-webserver
    protocol: TCP
    port: 8080
  loadBalancerSourceRanges:
    {{- range .Values.config.ode.sourceRanges }}
    - {{ . | title }}
    {{- end }}
  selector:
    app: jpoode-ode
---
apiVersion: v1
kind: Service
metadata:
  name: jpoode-ode-udp-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: jpoode-ode
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.config.ode.udp_service.ipAddress }}
  ports:
  - name: ode-rsu-bsm
    protocol: UDP
    port: 46800
  - name: ode-rsu-tim
    protocol: UDP
    port: 47900
  - name: ode-rsu-ssm
    protocol: UDP
    port: 44900
  - name: ode-rsu-spat
    protocol: UDP
    port: 44910
  - name: ode-rsu-map
    protocol: UDP
    port: 44920
  - name: ode-rsu-srm
    protocol: UDP
    port: 44930
  externalTrafficPolicy: Local
  selector:
    app: jpoode-ode
---
{{- if .Values.config.ode.udp_service.exposeExternally }}
apiVersion: v1
kind: Service
metadata:
  name: jpoode-ode-udp-svc-ext
  labels:
    app: jpoode-ode
spec:
  type: LoadBalancer
  ports:
  - name: ode-rsu-bsm
    protocol: UDP
    port: 46801
  - name: ode-rsu-tim
    protocol: UDP
    port: 47901
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    {{- range .Values.config.ode.sourceRanges }}
    - {{ . | title }}
    {{- end }}
  selector:
    app: jpoode-ode
{{- end }}
---
# ConfigMap for OpenSSH configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  sshd_config: |
    PasswordAuthentication no
    ChallengeResponseAuthentication no
  authorized_keys: |
    ssh-keys-goes-here
    each-key-goes-on-a-new-lines
    another-key
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "jpoode-ode"
  labels:
    app: "jpoode-ode"
spec:
  replicas: {{ .Values.replicas.jpoode_ode }}
  selector:
    matchLabels:
      app: "jpoode-ode"
  template:
    metadata:
      labels:
        app: "jpoode-ode"
    spec:
      containers:
        - name: "jpoode-ode-image-sha256-1"
          image: "{{ .Values.images.jpoode_ode.repository }}:{{ .Values.images.jpoode_ode.tag }}" 
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
          tty: true
          stdin: true
          ports:
          - containerPort: 22
          - containerPort: 8080
          - containerPort: 9090
          - containerPort: 46800
            protocol: UDP
          - containerPort: 47900
            protocol: UDP
            {{- if .Values.config.ode.udp_service.exposeExternally }}
          - containerPort: 46801
            protocol: UDP
          - containerPort: 47901
            protocol: UDP
            {{- end }}
          env:
          - name: DOCKER_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ODE_KAFKA_BROKERS
            value: {{ .Values.resources.services.kafka }}:9092
          - name: ZK
            value: {{ .Values.resources.services.zookeeper }}:2181
          - name: ODE_SECURITY_SVCS_SIGNATURE_URI
            value: {{ .Values.resources.services.security }}:8090
          - name: ODE_RSU_USERNAME
            valueFrom: 
              secretKeyRef:
                name: jpoode-secrets
                key: ode_rsu_username
          - name: ODE_RSU_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jpoode-secrets
                key: ode_rsu_password
          volumeMounts:
            - name: config-volume
              mountPath: /home/logging
            - name: ssh-volume
              subPath: sshd_config
              mountPath: /etc/ssh/sshd_config
            - name: ssh-volume
              subPath: authorized_keys
              mountPath: /root/.ssh/authorized_keys
            - name: obulog-volume
              mountPath: /home/uploads/backup
      volumes:
        - name: config-volume
          configMap:
            name: logback-conf
        - name: ssh-volume
          configMap:
            name: ssh-config
        - name: obulog-volume
          persistentVolumeClaim:
            claimName: filestore-pvc
