version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  steps:
    - run:
      name: Jacoco Tests
      command: |
        mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
