jobs:
  build:
    # Pull docker image 
    # XTERM used for better make output
    docker:
      - image: circleci/openjdk:8u252-jdk
        environment:
          TERM: xterm
          
    # Set working directory
    # working_directory: "/home/jpo-ode"
    # Pull code and execute tests |
    # Name of each run command defines purpose use
    steps:
      #setup remote docker
      - setup_remote_docker :
          docker_layer_caching: false
      # Checkout PR branch
      - checkout:
      - run:
          name: Initialize Submodules
          command: |
            set -x
            git submodule init
            git submodule update
      - run: 
          name: Run Maven Clean Package with Jacoco
          command: |
            mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
