version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8u252-jdk'
    steps:
      - checkout
      - run:
          name: Initialize Submodules
          command: |
            set -x
            git submodule init
            git submodule update
      - run:
          name: Analyze on SonarCloud
          command: mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

# version: 2

# #  Copyright (C) 2018-2020 LEIDOS.
# # 
# #  Licensed under the Apache License, Version 2.0 (the "License"); you may not
# #  use this file except in compliance with the License. You may obtain a copy of
# #  the License at
# # 
# #  http://www.apache.org/licenses/LICENSE-2.0
# # 
# #  Unless required by applicable law or agreed to in writing, software
# #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# #  License for the specific language governing permissions and limitations under
# #  the License.

# # Configuration file for Sonar Scanner used for CI 

# jobs:
#   build:
#     # Pull docker image 
#     # XTERM used for better make output
#     docker:
#       - image: circleci/openjdk:8u252-jdk
#         environment:
#           TERM: xterm
          
#     # Set working directory
#     # working_directory: "/home/jpo-ode"
#     # Pull code and execute tests |
#     # Name of each run command defines purpose use
#     steps:
#       #setup remote docker
#       - setup_remote_docker :
#           docker_layer_caching: false
#       # Checkout PR branch
#       - checkout:
#       - run:
#           name: Initialize Submodules
#           command: |
#             set -x
#             git submodule init
#             git submodule update
#       - run: 
#           name: Run Maven Clean Package with Jacoco
#           command: |
#             mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

# workflows:
#   main:
#     jobs:
#       - build:
#           context: SonarCloud