ode:
  host-ip: ${DOCKER_HOST_IP}
  kafka:
    brokers: ${DOCKER_HOST_IP}:9092
    producer-type: sync
    disabled-topics:
      - "topic.OdeBsmRxPojo"
      - "topic.OdeBsmTxPojo"
      - "topic.OdeBsmDuringEventPojo"
      - "topic.OdeTimBroadcastPojo"
    topics:
      asn1:
        decoder-input: "topic.Asn1DecoderInput"
        decoder-output: "topic.Asn1DecoderOutput"
        encoder-input: "topic.Asn1EncoderInput"
        encoder-output: "topic.Asn1EncoderOutput"
      broadcast:
        tim-pojo: "topic.OdeTimBroadcastPojo"
        tim-json: "topic.OdeTimBroadcastJson"
        tim-j2735-json: "topic.J2735TimBroadcastJson"
      cert-expiration:
        tim: "topic.OdeTIMCertExpirationTimeJson"
      during-event-pojo:
        bsm: "topic.OdeBsmDuringEventPojo"
      filtered-json:
        bsm: "topic.FilteredOdeBsmJson"
        spat: "topic.FilteredOdeSpatJson"
        tim: "topic.FilteredOdeTimJson"
      json:
        bsm: "topic.OdeBsmJson"
        map: "topic.OdeMapJson"
        psm: "topic.OdePsmJson"
        spat: "topic.OdeSpatJson"
        srm: "topic.OdeSrmJson"
        ssm: "topic.OdeSsmJson"
        tim: "topic.OdeTimJson"
        driver-alert: "topic.OdeDriverAlertJson"
      pojo:
        bsm: "topic.OdeBsmPojo"
        map:
        psm:
        spat: "topic.OdeSpatPojo"
        srm:
        ssm: "topic.OdeSsmPojo"
        tim:
      raw-encoded-json:
        bsm: "topic.OdeRawEncodedBSMJson"
        map: "topic.OdeRawEncodedMAPJson"
        psm: "topic.OdeRawEncodedPSMJson"
        spat: "topic.OdeRawEncodedSPATJson"
        srm: "topic.OdeRawEncodedSRMJson"
        ssm: "topic.OdeRawEncodedSSMJson"
        tim: "topic.OdeRawEncodedTIMJson"
      rx-pojo:
        bsm: "topic.OdeBsmRxPojo"
        spat: "topic.OdeSpatRxPojo"
      sdx-depositor:
        input: "topic.SDWDepositorInput"
      tx-pojo:
        bsm: "topic.OdeBsmTxPojo"
        map: "topic.OdeMapTxPojo"
        psm: "topic.OdePsmTxPojo"
        spat: "topic.OdeSpatTxPojo"
        srm: "topic.OdeSrmTxPojo"
  receivers:
    generic:
      buffer-size: 2000
      receiver-port: 44990
    bsm:
      buffer-size: 500
      receiver-port: 46800
    map:
      buffer-size: 2048
      receiver-port: 44920
    psm:
      buffer-size: 500
      receiver-port: 44940
    spat:
      buffer-size: 500
      receiver-port: 44910
    srm:
      buffer-size: 500
      receiver-port: 44930
    ssm:
      buffer-size: 500
      receiver-port: 44900
    tim:
      buffer-size: 500
      receiver-port: 47900
