ode:
  host-ip: ${DOCKER_HOST_IP}
  kafka:
    brokers: ${DOCKER_HOST_IP}:9092
    producer-type: sync
    disabled-topics:
      - "topic.OdeBsmRxPojo"
      - "topic.OdeBsmTxPojo"
      - "topic.OdeBsmDuringEventPojo"
      - "topic.OdeTimBroadcastPojo"
  bsm:
    receiver-port: 46800
    buffer-size: 500
    topics:
      pojo: "topic.OdeBsmPojo"
      json: "topic.OdeBsmJson"
      rx-pojo: "topic.OdeBsmRxPojo"
      tx-pojo: "topic.OdeBsmTxPojo"
      during-event-pojo: "topic.OdeBsmDuringEventPojo"
      filtered-json: "topic.FilteredOdeBsmJson"
      raw-encoded-json: "topic.OdeRawEncodedBSMJson"

