name: ci

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build
        uses: docker/build-push-action@v7
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max

  sonar:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Run Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -e clean verify sonar:sonar \
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY || 'usdot.jpo.ode:jpo-ode' }} \
            -Dsonar.projectName=jpo-ode \
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION || github.repository_owner }} \
            -Dsonar.host.url=https://sonarcloud.io
